### ISSUE TITLE
感谢大神修复imdb显示bug 烂番茄还是无法显示啊

### ISSUE THREAD

**Issue by yubowenlazio** [lisongx/doubanIMDb#11]
![QQ截图20190916065638](https://user-images.githubusercontent.com/20121349/64928780-5fa25180-d84f-11e9-8c29-5fa0b3bfb002.jpg)

**Comment by lisongx** [comment]
收到！明天我看一下，感谢反馈

**Comment by yubowenlazio** [comment]
大神 可能是我之前举得柯南的例子有错误 日本电影烂番茄很多都是没有的 但是英文电影烂番茄都有
![QQ截图20190924210606](https://user-images.githubusercontent.com/20121349/65514155-5aa86680-df0f-11e9-9b4e-166715c4b8b4.jpg)
这个可能不是bug 是烂番茄库的事

**Comment by yubowenlazio** [comment]
大神 我又来了 烂番茄好像又挂了。。。。。。莫名其妙啊
![QQ截图20190926225350](https://user-images.githubusercontent.com/20121349/65699360-90388580-e0b0-11e9-96ea-f80ed52377b7.jpg)

**Comment by lisongx** [comment]
@yubowenlazio
是不太稳定吗？这几天有出现问题吗

**Comment by yubowenlazio** [comment]
> @yubowenlazio
> 是不太稳定吗？这几天有出现问题吗

烂番茄不太稳定 尤其是网络比较拥挤的时候 IMDB一直很稳定

**Comment by lisongx** [comment]
现在是单纯抓去烂番茄的网站，可能会容易被ratelimit。
需要想个新办法

**Comment by lisongx** [comment]
@yubowenlazio 
Hi 你好，抱歉这么久才回复！

这几天做了一些服务器端优化，现在应该相对稳定了，🙏感谢反馈，可以尝试一下有没有更稳定
