### ISSUE TITLE
烂番茄评价无法显示

### ISSUE THREAD

**Issue by Jackeriss** [lisongx/doubanIMDb#8]
原位置显示为空白。

**Comment by seansay** [comment]
收到

**Comment by yubowenlazio** [comment]
是啊 烂番茄不显示了 求更新chrome啊 还有greasyfork上面没有大神的脚本啊 只在userscripts-mirror上面有

**Comment by seansay** [comment]
@yubowenlazio 
个人原因一直没有时间看这个问题……（greasyfork是？我不太清楚这个）

chrome我会抽时间看一下，实在抱歉

**Comment by yubowenlazio** [comment]
greasyfork里面都是脚本文件 好像现在这个比较流行 我不是专业的。。。。
大神态度太好了 chrome还得麻烦大神

**Comment by lisongx** [comment]
@yubowenlazio 
应该修复了！抱歉隔了这么久 😄

**Comment by lisongx** [comment]
如果还有问题可以再打开issue
